# Generated by Django 5.1.2 on 2024-10-25 16:51
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


def create_missing_user_profiles(apps, schema_editor):  # no cov
    UserProfile = apps.get_model('users', 'UserProfile')
    User = apps.get_model('auth', 'User')

    for user in User.objects.all():
        try:
            UserProfile.objects.get(user=user)
        except ObjectDoesNotExist:
            UserProfile.objects.create(user=user)


def remove_user_profiles(apps, schema_editor):  # no cov
    UserProfile = apps.get_model('users', 'UserProfile')
    for profile in UserProfile.objects.all():
        profile.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_missing_user_profiles, reverse_code=remove_user_profiles),
    ]
