# Generated by Django 5.1.2 on 2024-11-04 16:45
from django_q.models import Schedule
from django.db import migrations


def create_media_scheduled_tasks(apps, schema_editor):
    """Create a monthly task for deleting unreferenced media files."""
    Schedule_mod = apps.get_model('django_q', 'Schedule')
    clean_media_task = Schedule_mod.objects.create(
        func="play_different_games.core.tasks.remove_unreferenced_media_files",
        schedule_type=Schedule.MONTHLY,
        name="Remove unreferenced media files",
    )


def remove_scheduled_media_task(apps, schema_editor):
    """Delete any scheduled tasks for deleting media files"""
    Schedule_mod = apps.get_model('django_q', 'Schedule')
    tasks = Schedule_mod.objects.filter(func="play_different_games.core.tasks.remove_unreferenced_media_files")
    tasks.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("django_q", "0018_task_success_index"),
    ]

    operations = [migrations.RunPython(create_media_scheduled_tasks, reverse_code=remove_scheduled_media_task)]
